// src/boilerplates/svelte/codepan.svelte
<div id="app">
  <h2>{{ count }}</h2>
  <button on:click="inc()">Increment</button>
  <button on:click="dec()">Decrement</button>
</div>

<script>
export default {
  data() {
    return {
      count: 0
    }
  },

  methods: {
    inc() {
      this.set({
        count: this.get('count') + 1
      })
    },
    dec() {
      this.set({
        count: this.get('count') - 1
      })
    }
  }
}
</script>

// src/boilerplates/react/codepan.js
class App extends React.Component {
  state = {
    count: 0
  }

  inc = () =>
    this.setState({
      count: this.state.count + 1
    })

  dec = () =>
    this.setState({
      count: this.state.count - 1
    })

  render() {
    return (
      <div>
        <h2>{this.state.count}</h2>
        <button onClick={this.inc}>Increment</button>{' '}
        <button onClick={this.dec}>Decrement</button>
      </div>
    )
  }
}

ReactDOM.render(<App />, document.getElementById('app'))
